name: Ranking
version: '${version}'
main: fr.hephaisto.ranking.Ranking
authors: [ Hephaisto ]
description: Plugin for in game ranking
depend:
  - Factions
  - WorldOfNations
  - MassiveCore
  - Vault
commands:
  classement:
    description: Effectue le classement
    usage: /classement <faction>